In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
df=pd.read_csv('cardioActivities.csv',parse_dates=True,index_col='Date')

In [15]:
df.head()

,Activity Id,Type,Route Name,Distance (km),Duration,Average Pace,Average Speed (km/h),Calories Burned,Climb (m),Average Heart Rate (bpm),Friend's Tagged,Notes,GPX File
Date,,,,,,,,,,,,,
2018-11-11 14:05:12,c9627fed-14ac-47a2-bed3-2a2630c63c15,Running,NaN,10.44,58:40,5:37,10.68,774.0,130,159.0,NaN,NaN,2018-11-11-140512.gpx
2018-11-09 15:02:35,be65818d-a801-4847-a43b-2acdf4dc70e7,Running,NaN,12.84,1:14:12,5:47,10.39,954.0,168,159.0,NaN,NaN,2018-11-09-150235.gpx
2018-11-04 16:05:00,c09b2f92-f855-497c-b624-c196b3ef036c,Running,NaN,13.01,1:15:16,5:47,10.37,967.0,171,155.0,NaN,NaN,2018-11-04-160500.gpx
2018-11-01 14:03:58,bc9b612d-3499-43ff-b82a-9b17b71b8a36,Running,NaN,12.98,1:14:25,5:44,10.47,960.0,169,158.0,NaN,NaN,2018-11-01-140358.gpx
2018-10-27 17:01:36,972567b2-1b0e-437c-9e82-fef8078d6438,Running,NaN,13.02,1:12:50,5:36,10.73,967.0,170,154.0,NaN,NaN,2018-10-27-170136.gpx

In [16]:
df.dtypes

Activity Id                  object
Type                         object
Route Name                   object
Distance (km)               float64
Duration                     object
Average Pace                 object
Average Speed (km/h)        float64
Calories Burned             float64
Climb (m)                     int64
Average Heart Rate (bpm)    float64
Friend's Tagged             float64
Notes                        object
GPX File                     object
dtype: object

In [18]:
display(df.sample(3))

,Activity Id,Type,Route Name,Distance (km),Duration,Average Pace,Average Speed (km/h),Calories Burned,Climb (m),Average Heart Rate (bpm),Friend's Tagged,Notes,GPX File
Date,,,,,,,,,,,,,
2013-01-02 18:35:11,57ff5696-7610-4296-903a-88c63c207603,Running,NaN,5.47,31:24,5:45,10.44,392.000000,28,NaN,NaN,NaN,2013-01-02-183511.gpx
2016-07-10 16:35:25,85014381-7900-49e2-88f0-42c75e0954c1,Running,NaN,19.27,1:49:48,5:42,10.53,1323.999999,319,142.0,NaN,TomTom MySports Watch,2016-07-10-163525.gpx
2015-06-28 17:39:02,bdbd37a8-9c4f-41c4-9e87-1980a096881c,Running,NaN,19.81,1:55:57,5:51,10.25,1360.000000,313,133.0,NaN,NaN,2015-06-28-173902.gpx